import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
//import "../styles/globals"

export default function Layout({children}) {
  return (
    <div className="bg-rainbow min-h-screen">
      <Head>
        <title>Waar - Dein Gaming-Shop</title>
        <meta name="description" content="Generated by SMettel" />
      </Head>
      <Navbar />
      <div className="container" >
      {children}
      </div>
      <Footer />
    </div>
  );
}
