import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function Layout({children}) {
  return (
    <div>
      <Head>
        <title>Waar - Dein Gaming-Shop</title>
        <meta name="description" content="Generated by SMettel" />
      </Head>
      <Navbar />
      <div className="container">
      {children}
      </div>
      <Footer />
    </div>
  );
}
